<?xml version="1.0" encoding="utf-8"?><Database Name="OnlineShoppingDB" Class="OnlineShoppingDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=OnlineShoppingDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OnlineShoppingDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.company" Member="companies">
    <Type Name="company">
      <Column Name="companyID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="companyname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="username" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="dateofbirth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="district" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="subdistrict" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="province" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="zipcode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="telephone" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.deliverymethod" Member="deliverymethods">
    <Type Name="deliverymethod">
      <Column Name="deliverymethodID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="deliverymethodname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fee" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.genre" Member="genres">
    <Type Name="genre">
      <Column Name="genreID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="genrename" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.item" Member="items">
    <Type Name="item">
      <Column Name="itemID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="imageprofile" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="companyID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="platformID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="cost" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="sellingprice" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ratingID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="datemodified" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.itemgenre" Member="itemgenres">
    <Type Name="itemgenre">
      <Column Name="itemID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="genreID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.itemorder" Member="itemorders">
    <Type Name="itemorder">
      <Column Name="itemorderID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orderID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="itemID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="cost" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[order]" Member="orders">
    <Type Name="order">
      <Column Name="orderID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="orderstatusID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="deliverymethodID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.orderstatus" Member="orderstatus">
    <Type Name="orderstatus">
      <Column Name="orderstatusID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orderstatusname" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.picture" Member="pictures">
    <Type Name="picture">
      <Column Name="pictureID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="itemID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="itempicture" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.platform" Member="platforms">
    <Type Name="platform">
      <Column Name="platformID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="platformname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.rating" Member="ratings">
    <Type Name="rating">
      <Column Name="ratingID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ratingname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>